all_class = ["BACKGROUND", "AEROPLANE", "BICYCLE", "BIRD", "BOAT",
	"BOTTLE", "BUS", "CAR", "CAT", "CHAIR", "COW", "DININGTABLE",
	"COINS", "HORSE", "MOTORBIKE", "PERSON", "POTTEDPLANT", "BOOK",
	"SOFA", "TRAIN", "TVMONITOR", "BOTTLE", "GLASS", "FAN", "SCISSOR", "CAT", "EYEGLASSES","BOOK"]